### ISSUE TITLE
[cohend] Cohen's d in Common Language Explanation does not change

### ISSUE THREAD

**Issue by aosavi** [rpsychologist/rpsychologist-com#28]
The Cohen's _d_ in the Common Language Explanation doesn't seem to update. It remains .8, regardless of changes to _d_.

**Comment by rpsychologist** [comment]
Hmm, I can't reproduce this problem, what browser and OS are you using? It's rounded to 1 decimal tho
![cohend-CL](https://user-images.githubusercontent.com/1629860/110750318-97226c00-8242-11eb-884b-a588d1de49e2.gif)

**Comment by aosavi** [comment]
You're right, I didn't catch that. It feels a bit odd that the _d_ value doesn't change while the other values do, is there a reason for that? I noticed the slider shows 2 decimals up to _d_ = 1, and 1 decimal onward.

Thanks.

**Comment by rpsychologist** [comment]
I agree that it looks a bit odd - I'm gonna fix and and make the rounding a bit more consistent.

**Comment by aosavi** [comment]
And thanks for creating and sharing these fantastic visualizations!
