### ISSUE TITLE
Result labeled as "equivalent" when all points within the confidence interval are negative

### ISSUE THREAD

**Issue by josephalevin** [rpsychologist/rpsychologist-com#29]
First, I love the visualizations you've made. Thanks for sharing them.

Shouldn't the example below be labeled as "inferior"? The confidence interval is fully to the negative side. https://rpsychologist.com/d3/equivalence/

![image](https://user-images.githubusercontent.com/601472/111317975-ea425780-8664-11eb-8ce1-373e418bfe96.png)

A similar thing happens on the superior side.

**Comment by rpsychologist** [comment]
Thanks! The non-inferior, inferior, and equivalence test would all be significant in your example. I include only one test in the label to save space, but the other tests are highlighted in the chart. Tho it's mostly theoretical, you likely wouldn't set up an experiment that tests for inferiority, non-inferiority, and equivalence simultaneously.
