### ISSUE TITLE
Bug in correlation calculations after changing presets

### ISSUE THREAD

**Issue by xmddmx** [rpsychologist/rpsychologist-com#64]
Great project, I use it all the time!

Steps to reproduce:
* load https://rpsychologist.com/correlation/
* click Settings then the Anscombosaurus preset
* Everything looks fine
* Now change to the "Small" (r=0.1) preset

Results: r and r2 are incorrect as shown here:

<img width="924" alt="image" src="https://user-images.githubusercontent.com/107132172/219455791-1820b014-ffc1-45e2-aa65-bfbe21b4249a.png">

It looks like there is a point in the upper left of the data set which did not get reset?

**Comment by rpsychologist** [comment]
Thanks for reporting the bug!
